### ISSUE TITLE
Empty values not handled safely

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-parser-nmea0183#29]
For example:

```
$IIMWV,,,,*4C
TypeError: Cannot read property 'toUpperCase' of undefined
    at null._decoder (/home/pi/signalk-server-node/node_modules/nmea0183-signalk/codecs/MWV.js:59:14)
    at NMEA0183.decode (/home/pi/signalk-server-node/node_modules/nmea0183-signalk/lib/NMEA0183.js:236:24)
    at Parser._decode (/home/pi/signalk-server-node/node_modules/nmea0183-signalk/lib/index.js:107:44)
    at /home/pi/signalk-server-node/node_modules/nmea0183-signalk/lib/index.js:151:22
```

**Comment by fabdrol** [comment]
@tkurki I'll have a look at this asap, I'll let you know. I haven't encountered this one before, even though I have tested with empty values. Could be a regression in a newer codec.
