### ISSUE TITLE
Crash with corrupted data

### ISSUE THREAD

**Issue by sailoog** [SignalK/signalk-parser-nmea0183#88]
Some OpenPlotter users are experimenting crashes when trying to read corrupted data due to electrical problems or any devices malfuntion:

```
TypeError: Cannot read property 'toUpperCase' of undefined
    at NMEA0183._decoder (/home/pi/.config/signalk-server-node/node_modules/nmea0183-signalk/codecs/GLL.js:52:15)
    at NMEA0183.decode (/home/pi/.config/signalk-server-node/node_modules/nmea0183-signalk/lib/NMEA0183.js:259:26)
    at Parser._decode (/home/pi/.config/signalk-server-node/node_modules/nmea0183-signalk/lib/index.js:128:44)
    at /home/pi/.config/signalk-server-node/node_modules/nmea0183-signalk/lib/index.js:172:26
    at arrayEach (/home/pi/.config/signalk-server-node/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/home/pi/.config/signalk-server-node/node_modules/lodash/lodash.js:9359:14)
    at Parser._transform (/home/pi/.config/signalk-server-node/node_modules/nmea0183-signalk/lib/index.js:169:7)
    at Parser.Transform._read (_stream_transform.js:167:10)
    at Parser.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:331:12)
    at writeOrBuffer (_stream_writable.js:317:5)
    at Parser.Writable.write (_stream_writable.js:243:11)
    at ToSignalK._transform (/home/pi/.config/signalk-server-node/providers/nmea0183-signalk.js:68:19)
    at ToSignalK.Transform._read (_stream_transform.js:167:10)
    at ToSignalK.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:331:12)
```
Kplex and OpenCPN are digesting and showing what they are able to understand from these data but not crashing. Should not SK do the same? Attached a killer NMEA stream file.
[vdrfile1.txt](https://github.com/SignalK/signalk-parser-nmea0183/files/1128726/vdrfile1.txt)

**Comment by tkurki** [comment]
Thanks - let me know if this fixes the issue.

**Comment by sailoog** [comment]
It works perfectly, thanks!
